name: "Windows Builds"

on:
    push:
        branches:
            - 'main'

env:
    PHPUNIT_FLAGS: "-v"
#    SYMFONY_PHPUNIT_DIR: "$HOME/symfony-bridge/.phpunit"

jobs:
    test:
        name: "PHP ${{ matrix.php-version }}"

        runs-on: windows-latest

        strategy:
            fail-fast: false
            matrix:
                php-version:
                    - '8.1'

        steps:
            - name: "List Git Config"
              run: git config --global core.autocrlf input

            - name: "Checkout code"
              uses: actions/checkout@v2.3.3

            - name: "Install PHP with extensions"
              uses: shivammathur/setup-php@v2
              with:
                  coverage: "none"
                  php-version: ${{ matrix.php-version }}
                  tools: composer:v2
                  extensions: fileinfo, mbstring, openssl, curl

            - name: "Add PHPUnit matcher"
              run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: "Composer install"
              uses: "ramsey/composer-install@v1"

            - name: "PHPUnit version"
              run: vendor/bin/phpunit --version

            - name: "PHP Info"
              run: php -i

#            - name: "List Windows Env"
#              run: "Get-ChildItem Env: | Format-Table -Wrap -AutoSize"
#
            - name: "Run tests"
              run: vendor/bin/phpunit
